package ddt.utils{   import flash.display.BitmapData;   import flash.display.DisplayObject;   import flash.display.Shape;   import flash.events.Event;   import flash.geom.ColorTransform;   import flash.geom.Rectangle;   import times.utils.timerManager.TimerJuggler;   import times.utils.timerManager.TimerManager;      public class BitmapUtils   {            private static var _maskShape:Shape;            private static var _curX:Number;            private static var _curY:Number;            private static var _rowNumber:Number;            private static var _rowWitdh:Number;            private static var _rowHeight:Number;            private static var _frameStep:Number;            private static var _curRow:Number = 0;            private static var _sleepSecond:int = 0;            private static var _callBack:Function;            private static var _timer:TimerJuggler;            private static var _isMask:String;                   public function BitmapUtils() { super(); }
            public static function updateColor(source:BitmapData, color:Number) : BitmapData { return null; }
            public static function getHightlightColorTransfrom(color:uint) : ColorTransform { return null; }
            public static function setBitmapDataGray(src:BitmapData) : void { }
            public static function getColorTransfromByColor(color:uint) : ColorTransform { return null; }
            public static function maskMovie(source:DisplayObject, maskShape:Shape, isMask:String, rowNumber:Number, rowWitdh:Number, rowHeight:Number, frameStep:Number, sleepSecond:int, callBack:Function) : void { }
            private static function onMaskMovieEnerFrame(evt:Event) : void { }
            private static function onMaskMovieTimer(evt:Event) : void { }
            public static function reverseBtimapData(src:BitmapData) : void { }
   }}