package farm.view.compose{   import com.pickgliss.events.FrameEvent;   import com.pickgliss.ui.ComponentFactory;   import com.pickgliss.ui.controls.BaseButton;   import com.pickgliss.ui.controls.Frame;   import com.pickgliss.ui.controls.container.HBox;   import com.pickgliss.ui.image.Image;   import com.pickgliss.ui.image.Scale9CornerImage;   import com.pickgliss.ui.text.FilterFrameText;   import com.pickgliss.utils.ObjectUtils;   import ddt.data.goods.ItemTemplateInfo;   import ddt.manager.ItemManager;   import ddt.manager.LanguageMgr;   import ddt.manager.SoundManager;   import ddt.utils.PositionUtils;   import farm.control.FarmComposeHouseController;   import farm.view.compose.event.SelectComposeItemEvent;   import farm.view.compose.vo.FoodComposeListTemplateInfo;   import flash.display.Bitmap;   import flash.display.Sprite;   import flash.events.MouseEvent;   import shop.view.ShopItemCell;      public class ConfirmComposeFoodAlertFrame extends Frame   {                   private var _bg3:Scale9CornerImage;            private var _promptTxt:FilterFrameText;            private var _showTxtBG:Image;            private var _preBtn:BaseButton;            private var _nextBtn:BaseButton;            private var _hBox:HBox;            private var _cells:Vector.<ShopItemCell>;            private var _cellInfos:Array;            private var _currentPage:int;            private var _totlePage:int;            private var _currentImg:Bitmap;            public function ConfirmComposeFoodAlertFrame() { super(); }
            private function initView() : void { }
            private function initEvent() : void { }
            private function __onPageBtnClick(e:MouseEvent) : void { }
            private function initData() : void { }
            private function upCells(page:int = 0) : void { }
            private function __selectValue(e:MouseEvent) : void { }
            protected function __framePesponse(event:FrameEvent) : void { }
            private function removeEvent() : void { }
            override public function dispose() : void { }
   }}