package horse.view{   import baglocked.BaglockedManager;   import com.pickgliss.events.FrameEvent;   import com.pickgliss.ui.AlertManager;   import com.pickgliss.ui.ComponentFactory;   import com.pickgliss.ui.controls.SimpleBitmapButton;   import com.pickgliss.ui.controls.alert.BaseAlerFrame;   import com.pickgliss.ui.core.Disposeable;   import com.pickgliss.ui.text.FilterFrameText;   import com.pickgliss.utils.ObjectUtils;   import ddt.events.BagEvent;   import ddt.manager.ItemManager;   import ddt.manager.LanguageMgr;   import ddt.manager.MessageTipManager;   import ddt.manager.PlayerManager;   import ddt.manager.SocketManager;   import ddt.manager.SoundManager;   import ddt.manager.StateManager;   import ddt.utils.PositionUtils;   import ddt.view.horse.HorseFrameRightBottomItemCell;   import ddt.view.horse.HorseSkillCell;   import ddtDeed.DeedManager;   import flash.display.Bitmap;   import flash.display.Sprite;   import flash.events.Event;   import flash.events.MouseEvent;   import flash.events.TextEvent;   import flash.utils.getTimer;   import horse.HorseManager;   import horse.data.HorseEvent;   import horse.data.HorseSkillExpVo;   import horse.data.HorseSkillGetVo;   import shop.manager.ShopBuyManager;      public class HorseSkillUpFrame extends Sprite implements Disposeable   {                   private var _levelTxt:FilterFrameText;            private var _expBg:Bitmap;            private var _expCover:Bitmap;            private var _expPerTxt:FilterFrameText;            private var _txtBg:Bitmap;            private var _countTxt:FilterFrameText;            private var _maxBtn:SimpleBitmapButton;            private var _upBtn:SimpleBitmapButton;            private var _freeUpBtn:SimpleBitmapButton;            private var _freeUpTxt:FilterFrameText;            private var _curSkillCell:HorseSkillCell;            private var _upCurSkillCell:HorseSkillCell;            private var _upNextSkillCell:HorseSkillCell;            private var _upCurSkillLevelTxt:FilterFrameText;            private var _upNextSkillLevelTxt:FilterFrameText;            private var _itemCell:HorseFrameRightBottomItemCell;            private var _index:int;            private var _skillExp:HorseSkillExpVo;            private var _dataList:Vector.<HorseSkillGetVo>;            private var _lastUpClickTime:int = 0;            private var _maxCount:int;            private var _itemCount:int;            protected var _toLinkTxt:FilterFrameText;            public function HorseSkillUpFrame() { super(); }
            private function initView() : void { }
            public function __show(e:HorseEvent) : void { }
            private function refreshView(isReCell:Boolean = true) : void { }
            private function calMaxCountUpAndItem() : void { }
            private function initEvent() : void { }
            private function refreshFreeTipTxt(event:Event = null) : void { }
            private function itemUpdateHandler(event:BagEvent) : void { }
            private function upSkillSucHandler(event:Event) : void { }
            private function countTxtChangeHandler(event:Event) : void { }
            private function maxClickHandler(event:MouseEvent) : void { }
            private function upClickHandler(event:MouseEvent) : void { }
            private function buyConfirm(evt:FrameEvent) : void { }
            private function __responseHandler(evt:FrameEvent) : void { }
            private function removeEvent() : void { }
            private function __toLinkTxtHandler(evt:TextEvent) : void { }
            public function dispose() : void { }
   }}