package horse.amulet{   import baglocked.BaglockedManager;   import com.pickgliss.events.FrameEvent;   import com.pickgliss.ui.AlertManager;   import com.pickgliss.ui.ComponentFactory;   import com.pickgliss.ui.controls.BaseButton;   import com.pickgliss.ui.controls.SelectedCheckButton;   import com.pickgliss.ui.controls.SimpleBitmapButton;   import com.pickgliss.ui.controls.alert.BaseAlerFrame;   import com.pickgliss.ui.controls.container.HBox;   import com.pickgliss.ui.core.Disposeable;   import com.pickgliss.ui.image.NumberImage;   import com.pickgliss.ui.image.ScaleFrameImage;   import com.pickgliss.ui.text.FilterFrameText;   import com.pickgliss.utils.ObjectUtils;   import ddt.events.PkgEvent;   import ddt.events.PlayerPropertyEvent;   import ddt.manager.LanguageMgr;   import ddt.manager.MessageTipManager;   import ddt.manager.PlayerManager;   import ddt.manager.SocketManager;   import ddt.manager.SoundManager;   import ddt.utils.PositionUtils;   import flash.display.Bitmap;   import flash.display.Sprite;   import flash.events.Event;   import flash.events.MouseEvent;   import flash.utils.getTimer;   import horse.HorseAmuletManager;   import horse.data.HorseAmuletVo;      public class HorseAmuletActivateView extends Sprite implements Disposeable   {                   private var _bg:Bitmap;            private var _haveDustText:FilterFrameText;            private var _havaDustNumText:FilterFrameText;            private var _dustText:FilterFrameText;            private var _needDustText:FilterFrameText;            private var _extendTypeText:FilterFrameText;            private var _newExtendTypeText:FilterFrameText;            private var _propertyText:FilterFrameText;            private var _newPropertyText:FilterFrameText;            private var _helpText:FilterFrameText;            private var _activateBtn:SimpleBitmapButton;            private var _replaceBtn:BaseButton;            private var _cancelBtn:BaseButton;            private var _hBox:HBox;            private var _activateText:ScaleFrameImage;            private var _property:Bitmap;            private var _minCount:NumberImage;            private var _about:Bitmap;            private var _maxCount:NumberImage;            private var _activateCell:HorseAmuletActivateCell;            private var _resultIcon:ScaleFrameImage;            private var _currentTime:Number;            public function HorseAmuletActivateView() { super(); }
            private function init() : void { }
            private function initEvent() : void { }
            private function removeEvent() : void { }
            private function updateSatate(isActivate:Boolean) : void { }
            private function __propertyChange(evt:PlayerPropertyEvent) : void { }
            private function __onChangeCell(e:Event = null) : void { }
            private function __onUpdateActivate(e:PkgEvent) : void { }
            private function __onReplaceComplete(e:PkgEvent) : void { }
            private function __onSmashComplete(e:PkgEvent) : void { }
            private function __onClickActivate(e:MouseEvent) : void { }
            protected function __onSelectCheckClick(e:MouseEvent) : void { }
            private function __onAlertFrame(e:FrameEvent) : void { }
            private function __onClickReplace(e:MouseEvent) : void { }
            private function __onClickCancel(e:MouseEvent) : void { }
            public function dispose() : void { }
   }}