package com.yy.game{   import flash.display.Loader;   import flash.events.Event;   import flash.events.IOErrorEvent;   import flash.events.SecurityErrorEvent;   import flash.net.URLLoader;   import flash.net.URLLoaderDataFormat;   import flash.net.URLRequest;   import flash.net.URLRequestMethod;   import flash.net.URLVariables;   import flash.system.ApplicationDomain;   import flash.system.LoaderContext;   import flash.system.SecurityDomain;      public class GameMsgCollector   {            private static const SWF_LIB_URL:String = "http://client.garbage.game.yy.com/GameMsgCollectorLib.swf";            private static const CONFIG_URL:String = "http://client.garbage.game.yy.com/v.xml";            private static var _instance:GameMsgCollector;            public static const VERSION:String = "3.0";                   private var libInstance:Object = null;            private var toCallParamsMap:Object;            private var isIniting:Boolean = false;            public function GameMsgCollector(privateClass:PrivateClass) { super(); }
            public static function get instance() : GameMsgCollector { return null; }
            public function dispose() : void { }
            public function collectMessage(content:String, toUserRoleName:String, fromUserRoleName:String, msgType:String, gameSceneId:String, serverId:String, gameId:String, onSend:Function = null) : void { }
            public function getReportable(toUserRoleName:String, gameSceneId:String, serverId:String, gameId:String) : void { }
            public function reportGameProfile(passport:String, udbid:int, game:String, gameServer:String, roleName:String, roleLevel:int, gameEvent:String, otherParams:GameProfileParams = null) : void { }
            private function initLib(onInited:Function) : void { }
            private function loadLibSwf(version:String, onLoaded:Function) : void { }
            private function loadConfig(onLoaded:Function) : void { }
   }}class PrivateClass{          function PrivateClass() { super(); }
}