package petsBag.view.item{   import com.pickgliss.ui.ComponentFactory;   import com.pickgliss.ui.image.ScaleBitmapImage;   import com.pickgliss.ui.image.ScaleFrameImage;   import com.pickgliss.ui.text.FilterFrameText;   import com.pickgliss.ui.tip.BaseTip;   import com.pickgliss.utils.ObjectUtils;   import ddt.data.analyze.PetconfigAnalyzer;   import ddt.manager.LanguageMgr;   import flash.display.Sprite;   import pet.data.PetInfo;   import petsBag.PetsBagManager;      public class PetGrowUpTip extends BaseTip   {                   private var _name:FilterFrameText;            protected var _attackLbl:FilterFrameText;            protected var _attackTxt:FilterFrameText;            protected var _defenceLbl:FilterFrameText;            protected var _defenceTxt:FilterFrameText;            protected var _HPLbl:FilterFrameText;            protected var _HPTxt:FilterFrameText;            protected var _agilitykLbl:FilterFrameText;            protected var _agilityTxt:FilterFrameText;            protected var _luckLbl:FilterFrameText;            protected var _luckTxt:FilterFrameText;            private var _splitImg:ScaleBitmapImage;            protected var _bg:ScaleBitmapImage;            private var _container:Sprite;            private var _info:PetInfo;            private var _gradeImg:ScaleFrameImage;            private var LEADING:int = 5;            public function PetGrowUpTip() { super(); }
            override protected function init() : void { }
            private function fixPos() : void { }
            override protected function addChildren() : void { }
            override public function get tipData() : Object { return null; }
            override public function set tipData(data:Object) : void { }
            private function updateView() : void { }
            private function getProDatumIndex(datumValue:int) : int { return 0; }
            override public function dispose() : void { }
   }}