package ddt.manager{   import bagAndInfo.cell.BaseCell;   import com.greensock.TimelineLite;   import com.greensock.TweenMax;   import com.greensock.easing.Sine;   import com.pickgliss.toplevel.StageReferance;   import com.pickgliss.ui.ComponentFactory;   import com.pickgliss.ui.core.Disposeable;   import com.pickgliss.utils.ClassUtils;   import com.pickgliss.utils.ObjectUtils;   import ddt.data.TweenVars;   import ddt.data.goods.InventoryItemInfo;   import ddt.data.goods.ItemTemplateInfo;   import flash.display.DisplayObject;   import flash.display.DisplayObjectContainer;   import flash.display.MovieClip;   import flash.display.Sprite;   import flash.geom.Point;   import flash.utils.clearTimeout;   import flash.utils.setTimeout;   import road7th.utils.MovieClipWrapper;      public class DropGoodsManager implements Disposeable   {            private static var _isEmailAniam:Boolean = true;                   public var parentContainer:DisplayObjectContainer;            public var beginPoint:Point;            public var endPoint:Point;            private var goodsList:Vector.<ItemTemplateInfo>;            private var timeOutIdArr:Array;            private var tweenArr:Array;            private var intervalId:uint;            private var goodsTipList:Vector.<ItemTemplateInfo>;            private var _info:InventoryItemInfo;            public function DropGoodsManager(begin:Point, end:Point) { super(); }
            public static function play(item:Array, begin:Point = null, end:Point = null, isEmailAniam:Boolean = false) : void { }
            private function onPetCompletePackUp(goods:DisplayObject) : void { }
            private function packUp(goods:DisplayObject, callBack:Function) : void { }
            private function onCompletePackUp(goods:DisplayObject) : void { }
            private function getBagAniam() : MovieClipWrapper { return null; }
            private function getEmailAniam() : MovieClipWrapper { return null; }
            private function setGoodsList(item:Array) : void { }
            public function dispose() : void { }
   }}