package dragonBones.factories{   import dragonBones.Armature;   import dragonBones.Slot;   import dragonBones.display.StarlingFastSlot;   import dragonBones.display.StarlingSlot;   import dragonBones.fast.FastArmature;   import dragonBones.fast.FastSlot;   import dragonBones.textures.ITextureAtlas;   import dragonBones.textures.StarlingTextureAtlas;   import flash.display.BitmapData;   import flash.display.MovieClip;   import flash.geom.Rectangle;   import flash.utils.Dictionary;   import road7th.DDTAssetManager;   import starling.core.Starling;   import starling.display.Image;   import starling.display.Sprite;   import starling.textures.SubTexture;   import starling.textures.Texture;   import starling.textures.TextureAtlas;      public class StarlingFactory extends BaseFactory   {                   public var generateMipMaps:Boolean;            public var optimizeForRenderToTexture:Boolean;            public var scaleForTexture:Number;            public function StarlingFactory() { super(null); }
            override protected function generateTextureAtlas(content:Object, textureAtlasRawData:Object) : ITextureAtlas { return null; }
            override protected function generateArmature() : Armature { return null; }
            override protected function generateFastArmature() : FastArmature { return null; }
            override protected function generateSlot() : Slot { return null; }
            override protected function generateFastSlot() : FastSlot { return null; }
            override protected function generateDisplay(textureAtlas:Object, fullName:String, pivotX:Number, pivotY:Number) : Object { return null; }
            private function getNearest2N(_n:uint) : uint { return null; }
            override protected function get textureAtlasDic() : Dictionary { return null; }
   }}