package itemActivityGift{   import com.pickgliss.events.FrameEvent;   import com.pickgliss.ui.AlertManager;   import com.pickgliss.ui.controls.alert.BaseAlerFrame;   import com.pickgliss.utils.ObjectUtils;   import ddt.data.goods.InventoryItemInfo;   import ddt.events.CrazyTankSocketEvent;   import ddt.manager.LanguageMgr;   import ddt.manager.LeavePageManager;   import ddt.manager.MessageTipManager;   import ddt.manager.PlayerManager;   import ddt.manager.ServerConfigManager;   import ddt.manager.SocketManager;   import ddt.manager.SoundManager;   import ddt.manager.TimeManager;   import flash.events.EventDispatcher;   import flash.events.IEventDispatcher;   import flash.utils.Dictionary;   import itemActivityGift.data.ItemEveryDayRecordData;   import itemActivityGift.model.ItemActivityGiftModel;   import road7th.comm.PackageIn;      public class ItemActivityGiftManager extends EventDispatcher   {            private static var _instance:ItemActivityGiftManager;                   private var _model:ItemActivityGiftModel;            private var frameObj:Object;            private var frameType:int;            private var tipsFrame:BaseAlerFrame;            public function ItemActivityGiftManager(target:IEventDispatcher = null) { super(null); }
            public static function get instance() : ItemActivityGiftManager { return null; }
            public function get model() : ItemActivityGiftModel { return null; }
            public function setup() : void { }
            private function __itemActivityGiftDataHandler(event:CrazyTankSocketEvent) : void { }
            private function everyDayGiftRecordDataHandler(pkg:PackageIn) : void { }
            public function showFrame($frameType:int, $frameObj:Object = null) : void { }
            private function __onFrameResponse(evt:FrameEvent) : void { }
            private function tipsDispose() : void { }
   }}